var number = 10;
console.log(number);
let userName = "jagriti";
console.log(userName);
const userId = true;
console.log(userId);
let location = false;
// let salary = nulll;
console.log(typeof ( location, userName));
const car = ["volvo", "BMW", "range rover "];
console.log(car);
userName = "chaudhray";
console.log(userName);
userId = false;
console.log(userId);
